# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

Name: Excel Viewer
Id: GrapeCity.gc-excelviewer
Description: Edit Excel spreadsheets and CSV files in Visual Studio Code and VS Code for the Web.
Version: 4.2.59
Publisher: MESCIUS
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=GrapeCity.gc-excelviewer
